# Generated by Django 3.2.6 on 2021-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_dog_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
