# Generated by Django 3.2.6 on 2021-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dog_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
